"""empty message

Revision ID: af898d0f21f6
Revises: 50be7444cb68
Create Date: 2020-02-05 18:20:26.368114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af898d0f21f6'
down_revision = '50be7444cb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_correlation', sa.Column('whois', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_correlation', 'whois')
    # ### end Alembic commands ###
