"""add root_cause table

Revision ID: f4085f9e7d30
Revises: 43a8981785b5
Create Date: 2020-01-30 14:08:44.252772

"""
from alembic import op
import sqlalchemy as sa
from db.models import ChoiceType


# revision identifiers, used by Alembic.
revision = 'f4085f9e7d30'
down_revision = '43a8981785b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=True),
    sa.Column('policy', ChoiceType({}), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ip_correlation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_ip', sa.Integer(), nullable=True),
    sa.Column('remote_ip', sa.String(length=16), nullable=True),
    sa.Column('treatment', ChoiceType({}), nullable=False),
    sa.ForeignKeyConstraint(['local_ip'], ['local_ip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_correlation')
    op.drop_table('local_ip')
    # ### end Alembic commands ###
